### ISSUE TITLE
Provide some sample IL files

### ISSUE THREAD

**Issue by awick** [cisagov/parsnip#22]
# 💡 Summary #

Can you provide some semi-complete sample IL files for real protocols? I would like to add Arkime support.

## Motivation and context ##

I'm hoping you have already prototyped some protocols in parsnip. I would like to use the IL files to generate code that Arkime can use. I don't need the generated spicy code, I would need to work with the IL files since in JSON.

## Implementation notes ##

Maybe make a samples directory?

## Acceptance criteria ##

- [x] Some sample IL files are checked in, hopefully for a protocol that it is easy to find pcap for

**Comment by piercema** [comment]
That is a great idea. We are preparing to release our first parser prepared with Parsnip in the next two weeks. We will include the intermediate language files in the release as well as several PCAPs we have used to test.

**Comment by piercema** [comment]
Our first parser built with Parsnip was made public today. The associated intermediate language files are found inside the repository here(https://github.com/cisagov/icsnpp-hart-ip/tree/main/parsnip_files/intermediate_language).

**Comment by mmguero** [comment]
Probably also want to have the [documentation](https://github.com/cisagov/parsnip/tree/main/docs) as a reference.

**Comment by nagilum2007** [comment]
Further discussions in the discussion board.
